Update requirements.txt to add new packages
Since requirements.txt didn't pin either package, pip installed
whichever version was newest at build time, which caused both of
the below errors. Pinned both compatible to selenium-wire. If we can just use selenium import webdriver instead of selenium-wire this can be reverted.
ModuleNotFoundError: No module named 'blinker._saferef' when trying to import seleniumwire
AttributeError: 'X509' object has no attribute 'get_extension'